sonar.projectKey=Jonathangadeaharder_Songster
sonar.organization=jonathangadeaharder

sonar.exclusions=tests/**,test-results/**,**/*.test.ts,**/*.spec.ts
sonar.cpd.exclusions=tests/**,**/*.test.ts,**/*.spec.ts
